<?php

namespace Bugloos\LaravelLocalization\database\seeders;

use Bugloos\LaravelLocalization\Models\Language;
use Bugloos\LaravelLocalization\Traits\ConfiguredTableName;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageSeeder extends Seeder
{
    use ConfiguredTableName;

    public function run()
    {
        DB::table($this->getTable(Language::class))->insert($this->languages());
    }

    private function languages()
    {
        return [
            ["locale" => "af", "name" => "Afrikaans"],
            ["locale" => "af_NA", "name" => "Afrikaans (Namibia)"],
            ["locale" => "af_ZA", "name" => "Afrikaans (South Africa)"],
            ["locale" => "ak", "name" => "Akan"],
            ["locale" => "ak_GH", "name" => "Akan (Ghana)"],
            ["locale" => "sq", "name" => "Albanian"],
            ["locale" => "sq_AL", "name" => "Albanian (Albania)"],
            ["locale" => "sq_XK", "name" => "Albanian (Kosovo)"],
            ["locale" => "sq_MK", "name" => "Albanian (Macedonia)"],
            ["locale" => "am", "name" => "Amharic"],
            ["locale" => "am_ET", "name" => "Amharic (Ethiopia)"],
            ["locale" => "ar", "name" => "Arabic"],
            ["locale" => "ar_DZ", "name" => "Arabic (Algeria)"],
            ["locale" => "ar_BH", "name" => "Arabic (Bahrain)"],
            ["locale" => "ar_TD", "name" => "Arabic (Chad)"],
            ["locale" => "ar_KM", "name" => "Arabic (Comoros)"],
            ["locale" => "ar_DJ", "name" => "Arabic (Djibouti)"],
            ["locale" => "ar_EG", "name" => "Arabic (Egypt)"],
            ["locale" => "ar_ER", "name" => "Arabic (Eritrea)"],
            ["locale" => "ar_IQ", "name" => "Arabic (Iraq)"],
            ["locale" => "ar_IL", "name" => "Arabic (Israel)"],
            ["locale" => "ar_JO", "name" => "Arabic (Jordan)"],
            ["locale" => "ar_KW", "name" => "Arabic (Kuwait)"],
            ["locale" => "ar_LB", "name" => "Arabic (Lebanon)"],
            ["locale" => "ar_LY", "name" => "Arabic (Libya)"],
            ["locale" => "ar_MR", "name" => "Arabic (Mauritania)"],
            ["locale" => "ar_MA", "name" => "Arabic (Morocco)"],
            ["locale" => "ar_OM", "name" => "Arabic (Oman)"],
            ["locale" => "ar_PS", "name" => "Arabic (Palestinian Territories)"],
            ["locale" => "ar_QA", "name" => "Arabic (Qatar)"],
            ["locale" => "ar_SA", "name" => "Arabic (Saudi Arabia)"],
            ["locale" => "ar_SO", "name" => "Arabic (Somalia)"],
            ["locale" => "ar_SS", "name" => "Arabic (South Sudan)"],
            ["locale" => "ar_SD", "name" => "Arabic (Sudan)"],
            ["locale" => "ar_SY", "name" => "Arabic (Syria)"],
            ["locale" => "ar_TN", "name" => "Arabic (Tunisia)"],
            ["locale" => "ar_AE", "name" => "Arabic (United Arab Emirates)"],
            ["locale" => "ar_EH", "name" => "Arabic (Western Sahara)"],
            ["locale" => "ar_YE", "name" => "Arabic (Yemen)"],
            ["locale" => "hy", "name" => "Armenian"],
            ["locale" => "hy_AM", "name" => "Armenian (Armenia)"],
            ["locale" => "as", "name" => "Assamese"],
            ["locale" => "as_IN", "name" => "Assamese (India)"],
            ["locale" => "az", "name" => "Azerbaijani"],
            ["locale" => "az_AZ", "name" => "Azerbaijani (Azerbaijan)"],
            ["locale" => "az_Cyrl_AZ", "name" => "Azerbaijani (Cyrillic, Azerbaijan)"],
            ["locale" => "az_Cyrl", "name" => "Azerbaijani (Cyrillic)"],
            ["locale" => "az_Latn_AZ", "name" => "Azerbaijani (Latin, Azerbaijan)"],
            ["locale" => "az_Latn", "name" => "Azerbaijani (Latin)"],
            ["locale" => "bm", "name" => "Bambara"],
            ["locale" => "bm_Latn_ML", "name" => "Bambara (Latin, Mali)"],
            ["locale" => "bm_Latn", "name" => "Bambara (Latin)"],
            ["locale" => "eu", "name" => "Basque"],
            ["locale" => "eu_ES", "name" => "Basque (Spain)"],
            ["locale" => "be", "name" => "Belarusian"],
            ["locale" => "be_BY", "name" => "Belarusian (Belarus)"],
            ["locale" => "bn", "name" => "Bengali"],
            ["locale" => "bn_BD", "name" => "Bengali (Bangladesh)"],
            ["locale" => "bn_IN", "name" => "Bengali (India)"],
            ["locale" => "bs", "name" => "Bosnian"],
            ["locale" => "bs_BA", "name" => "Bosnian (Bosnia & Herzegovina)"],
            [
                "locale" => "bs_Cyrl_BA",
                "name" => "Bosnian (Cyrillic, Bosnia & Herzegovina)",
            ],
            ["locale" => "bs_Cyrl", "name" => "Bosnian (Cyrillic)"],
            [
                "locale" => "bs_Latn_BA",
                "name" => "Bosnian (Latin, Bosnia & Herzegovina)",
            ],
            ["locale" => "bs_Latn", "name" => "Bosnian (Latin)"],
            ["locale" => "br", "name" => "Breton"],
            ["locale" => "br_FR", "name" => "Breton (France)"],
            ["locale" => "bg", "name" => "Bulgarian"],
            ["locale" => "bg_BG", "name" => "Bulgarian (Bulgaria)"],
            ["locale" => "my", "name" => "Burmese"],
            ["locale" => "my_MM", "name" => "Burmese (Myanmar (Burma))"],
            ["locale" => "ca", "name" => "Catalan"],
            ["locale" => "ca_AD", "name" => "Catalan (Andorra)"],
            ["locale" => "ca_FR", "name" => "Catalan (France)"],
            ["locale" => "ca_IT", "name" => "Catalan (Italy)"],
            ["locale" => "ca_ES", "name" => "Catalan (Spain)"],
            ["locale" => "zh", "name" => "Chinese"],
            ["locale" => "zh_CN", "name" => "Chinese (China)"],
            ["locale" => "zh_HK", "name" => "Chinese (Hong Kong SAR China)"],
            ["locale" => "zh_MO", "name" => "Chinese (Macau SAR China)"],
            ["locale" => "zh_Hans_CN", "name" => "Chinese (Simplified, China)"],
            [
                "locale" => "zh_Hans_HK",
                "name" => "Chinese (Simplified, Hong Kong SAR China)",
            ],
            [
                "locale" => "zh_Hans_MO",
                "name" => "Chinese (Simplified, Macau SAR China)",
            ],
            ["locale" => "zh_Hans_SG", "name" => "Chinese (Simplified, Singapore)"],
            ["locale" => "zh_Hans", "name" => "Chinese (Simplified)"],
            ["locale" => "zh_SG", "name" => "Chinese (Singapore)"],
            ["locale" => "zh_TW", "name" => "Chinese (Taiwan)"],
            [
                "locale" => "zh_Hant_HK",
                "name" => "Chinese (Traditional, Hong Kong SAR China)",
            ],
            [
                "locale" => "zh_Hant_MO",
                "name" => "Chinese (Traditional, Macau SAR China)",
            ],
            ["locale" => "zh_Hant_TW", "name" => "Chinese (Traditional, Taiwan)"],
            ["locale" => "zh_Hant", "name" => "Chinese (Traditional)"],
            ["locale" => "kw", "name" => "Cornish"],
            ["locale" => "kw_GB", "name" => "Cornish (United Kingdom)"],
            ["locale" => "hr", "name" => "Croatian"],
            ["locale" => "hr_BA", "name" => "Croatian (Bosnia & Herzegovina)"],
            ["locale" => "hr_HR", "name" => "Croatian (Croatia)"],
            ["locale" => "cs", "name" => "Czech"],
            ["locale" => "cs_CZ", "name" => "Czech (Czech Republic)"],
            ["locale" => "da", "name" => "Danish"],
            ["locale" => "da_DK", "name" => "Danish (Denmark)"],
            ["locale" => "da_GL", "name" => "Danish (Greenland)"],
            ["locale" => "nl", "name" => "Dutch"],
            ["locale" => "nl_AW", "name" => "Dutch (Aruba)"],
            ["locale" => "nl_BE", "name" => "Dutch (Belgium)"],
            ["locale" => "nl_BQ", "name" => "Dutch (Caribbean Netherlands)"],
            ["locale" => "nl_CW", "name" => "Dutch (Curaçao)"],
            ["locale" => "nl_NL", "name" => "Dutch (Netherlands)"],
            ["locale" => "nl_SX", "name" => "Dutch (Sint Maarten)"],
            ["locale" => "nl_SR", "name" => "Dutch (Suriname)"],
            ["locale" => "dz", "name" => "Dzongkha"],
            ["locale" => "dz_BT", "name" => "Dzongkha (Bhutan)"],
            ["locale" => "en", "name" => "English"],
            ["locale" => "en_AS", "name" => "English (American Samoa)"],
            ["locale" => "en_AI", "name" => "English (Anguilla)"],
            ["locale" => "en_AG", "name" => "English (Antigua & Barbuda)"],
            ["locale" => "en_AU", "name" => "English (Australia)"],
            ["locale" => "en_BS", "name" => "English (Bahamas)"],
            ["locale" => "en_BB", "name" => "English (Barbados)"],
            ["locale" => "en_BE", "name" => "English (Belgium)"],
            ["locale" => "en_BZ", "name" => "English (Belize)"],
            ["locale" => "en_BM", "name" => "English (Bermuda)"],
            ["locale" => "en_BW", "name" => "English (Botswana)"],
            ["locale" => "en_IO", "name" => "English (British Indian Ocean Territory)"],
            ["locale" => "en_VG", "name" => "English (British Virgin Islands)"],
            ["locale" => "en_CM", "name" => "English (Cameroon)"],
            ["locale" => "en_CA", "name" => "English (Canada)"],
            ["locale" => "en_KY", "name" => "English (Cayman Islands)"],
            ["locale" => "en_CX", "name" => "English (Christmas Island)"],
            ["locale" => "en_CC", "name" => "English (Cocos (Keeling) Islands)"],
            ["locale" => "en_CK", "name" => "English (Cook Islands)"],
            ["locale" => "en_DG", "name" => "English (Diego Garcia)"],
            ["locale" => "en_DM", "name" => "English (Dominica)"],
            ["locale" => "en_ER", "name" => "English (Eritrea)"],
            ["locale" => "en_FK", "name" => "English (Falkland Islands)"],
            ["locale" => "en_FJ", "name" => "English (Fiji)"],
            ["locale" => "en_GM", "name" => "English (Gambia)"],
            ["locale" => "en_GH", "name" => "English (Ghana)"],
            ["locale" => "en_GI", "name" => "English (Gibraltar)"],
            ["locale" => "en_GD", "name" => "English (Grenada)"],
            ["locale" => "en_GU", "name" => "English (Guam)"],
            ["locale" => "en_GG", "name" => "English (Guernsey)"],
            ["locale" => "en_GY", "name" => "English (Guyana)"],
            ["locale" => "en_HK", "name" => "English (Hong Kong SAR China)"],
            ["locale" => "en_IN", "name" => "English (India)"],
            ["locale" => "en_IE", "name" => "English (Ireland)"],
            ["locale" => "en_IM", "name" => "English (Isle of Man)"],
            ["locale" => "en_JM", "name" => "English (Jamaica)"],
            ["locale" => "en_JE", "name" => "English (Jersey)"],
            ["locale" => "en_KE", "name" => "English (Kenya)"],
            ["locale" => "en_KI", "name" => "English (Kiribati)"],
            ["locale" => "en_LS", "name" => "English (Lesotho)"],
            ["locale" => "en_LR", "name" => "English (Liberia)"],
            ["locale" => "en_MO", "name" => "English (Macau SAR China)"],
            ["locale" => "en_MG", "name" => "English (Madagascar)"],
            ["locale" => "en_MW", "name" => "English (Malawi)"],
            ["locale" => "en_MY", "name" => "English (Malaysia)"],
            ["locale" => "en_MT", "name" => "English (Malta)"],
            ["locale" => "en_MH", "name" => "English (Marshall Islands)"],
            ["locale" => "en_MU", "name" => "English (Mauritius)"],
            ["locale" => "en_FM", "name" => "English (Micronesia)"],
            ["locale" => "en_MS", "name" => "English (Montserrat)"],
            ["locale" => "en_NA", "name" => "English (Namibia)"],
            ["locale" => "en_NR", "name" => "English (Nauru)"],
            ["locale" => "en_NZ", "name" => "English (New Zealand)"],
            ["locale" => "en_NG", "name" => "English (Nigeria)"],
            ["locale" => "en_NU", "name" => "English (Niue)"],
            ["locale" => "en_NF", "name" => "English (Norfolk Island)"],
            ["locale" => "en_MP", "name" => "English (Northern Mariana Islands)"],
            ["locale" => "en_PK", "name" => "English (Pakistan)"],
            ["locale" => "en_PW", "name" => "English (Palau)"],
            ["locale" => "en_PG", "name" => "English (Papua New Guinea)"],
            ["locale" => "en_PH", "name" => "English (Philippines)"],
            ["locale" => "en_PN", "name" => "English (Pitcairn Islands)"],
            ["locale" => "en_PR", "name" => "English (Puerto Rico)"],
            ["locale" => "en_RW", "name" => "English (Rwanda)"],
            ["locale" => "en_WS", "name" => "English (Samoa)"],
            ["locale" => "en_SC", "name" => "English (Seychelles)"],
            ["locale" => "en_SL", "name" => "English (Sierra Leone)"],
            ["locale" => "en_SG", "name" => "English (Singapore)"],
            ["locale" => "en_SX", "name" => "English (Sint Maarten)"],
            ["locale" => "en_SB", "name" => "English (Solomon Islands)"],
            ["locale" => "en_ZA", "name" => "English (South Africa)"],
            ["locale" => "en_SS", "name" => "English (South Sudan)"],
            ["locale" => "en_SH", "name" => "English (St. Helena)"],
            ["locale" => "en_KN", "name" => "English (St. Kitts & Nevis)"],
            ["locale" => "en_LC", "name" => "English (St. Lucia)"],
            ["locale" => "en_VC", "name" => "English (St. Vincent & Grenadines)"],
            ["locale" => "en_SD", "name" => "English (Sudan)"],
            ["locale" => "en_SZ", "name" => "English (Swaziland)"],
            ["locale" => "en_TZ", "name" => "English (Tanzania)"],
            ["locale" => "en_TK", "name" => "English (Tokelau)"],
            ["locale" => "en_TO", "name" => "English (Tonga)"],
            ["locale" => "en_TT", "name" => "English (Trinidad & Tobago)"],
            ["locale" => "en_TC", "name" => "English (Turks & Caicos Islands)"],
            ["locale" => "en_TV", "name" => "English (Tuvalu)"],
            ["locale" => "en_UM", "name" => "English (U.S. Outlying Islands)"],
            ["locale" => "en_VI", "name" => "English (U.S. Virgin Islands)"],
            ["locale" => "en_UG", "name" => "English (Uganda)"],
            ["locale" => "en_GB", "name" => "English (United Kingdom)"],
            ["locale" => "en_US", "name" => "English (United States)"],
            ["locale" => "en_VU", "name" => "English (Vanuatu)"],
            ["locale" => "en_ZM", "name" => "English (Zambia)"],
            ["locale" => "en_ZW", "name" => "English (Zimbabwe)"],
            ["locale" => "eo", "name" => "Esperanto"],
            ["locale" => "et", "name" => "Estonian"],
            ["locale" => "et_EE", "name" => "Estonian (Estonia)"],
            ["locale" => "ee", "name" => "Ewe"],
            ["locale" => "ee_GH", "name" => "Ewe (Ghana)"],
            ["locale" => "ee_TG", "name" => "Ewe (Togo)"],
            ["locale" => "fo", "name" => "Faroese"],
            ["locale" => "fo_FO", "name" => "Faroese (Faroe Islands)"],
            ["locale" => "fi", "name" => "Finnish"],
            ["locale" => "fi_FI", "name" => "Finnish (Finland)"],
            ["locale" => "fr", "name" => "French"],
            ["locale" => "fr_DZ", "name" => "French (Algeria)"],
            ["locale" => "fr_BE", "name" => "French (Belgium)"],
            ["locale" => "fr_BJ", "name" => "French (Benin)"],
            ["locale" => "fr_BF", "name" => "French (Burkina Faso)"],
            ["locale" => "fr_BI", "name" => "French (Burundi)"],
            ["locale" => "fr_CM", "name" => "French (Cameroon)"],
            ["locale" => "fr_CA", "name" => "French (Canada)"],
            ["locale" => "fr_CF", "name" => "French (Central African Republic)"],
            ["locale" => "fr_TD", "name" => "French (Chad)"],
            ["locale" => "fr_KM", "name" => "French (Comoros)"],
            ["locale" => "fr_CG", "name" => "French (Congo - Brazzaville)"],
            ["locale" => "fr_CD", "name" => "French (Congo - Kinshasa)"],
            ["locale" => "fr_CI", "name" => "French (Côte d’Ivoire)"],
            ["locale" => "fr_DJ", "name" => "French (Djibouti)"],
            ["locale" => "fr_GQ", "name" => "French (Equatorial Guinea)"],
            ["locale" => "fr_FR", "name" => "French (France)"],
            ["locale" => "fr_GF", "name" => "French (French Guiana)"],
            ["locale" => "fr_PF", "name" => "French (French Polynesia)"],
            ["locale" => "fr_GA", "name" => "French (Gabon)"],
            ["locale" => "fr_GP", "name" => "French (Guadeloupe)"],
            ["locale" => "fr_GN", "name" => "French (Guinea)"],
            ["locale" => "fr_HT", "name" => "French (Haiti)"],
            ["locale" => "fr_LU", "name" => "French (Luxembourg)"],
            ["locale" => "fr_MG", "name" => "French (Madagascar)"],
            ["locale" => "fr_ML", "name" => "French (Mali)"],
            ["locale" => "fr_MQ", "name" => "French (Martinique)"],
            ["locale" => "fr_MR", "name" => "French (Mauritania)"],
            ["locale" => "fr_MU", "name" => "French (Mauritius)"],
            ["locale" => "fr_YT", "name" => "French (Mayotte)"],
            ["locale" => "fr_MC", "name" => "French (Monaco)"],
            ["locale" => "fr_MA", "name" => "French (Morocco)"],
            ["locale" => "fr_NC", "name" => "French (New Caledonia)"],
            ["locale" => "fr_NE", "name" => "French (Niger)"],
            ["locale" => "fr_RE", "name" => "French (Réunion)"],
            ["locale" => "fr_RW", "name" => "French (Rwanda)"],
            ["locale" => "fr_SN", "name" => "French (Senegal)"],
            ["locale" => "fr_SC", "name" => "French (Seychelles)"],
            ["locale" => "fr_BL", "name" => "French (St. Barthélemy)"],
            ["locale" => "fr_MF", "name" => "French (St. Martin)"],
            ["locale" => "fr_PM", "name" => "French (St. Pierre & Miquelon)"],
            ["locale" => "fr_CH", "name" => "French (Switzerland)"],
            ["locale" => "fr_SY", "name" => "French (Syria)"],
            ["locale" => "fr_TG", "name" => "French (Togo)"],
            ["locale" => "fr_TN", "name" => "French (Tunisia)"],
            ["locale" => "fr_VU", "name" => "French (Vanuatu)"],
            ["locale" => "fr_WF", "name" => "French (Wallis & Futuna)"],
            ["locale" => "ff", "name" => "Fulah"],
            ["locale" => "ff_CM", "name" => "Fulah (Cameroon)"],
            ["locale" => "ff_GN", "name" => "Fulah (Guinea)"],
            ["locale" => "ff_MR", "name" => "Fulah (Mauritania)"],
            ["locale" => "ff_SN", "name" => "Fulah (Senegal)"],
            ["locale" => "gl", "name" => "Galician"],
            ["locale" => "gl_ES", "name" => "Galician (Spain)"],
            ["locale" => "lg", "name" => "Ganda"],
            ["locale" => "lg_UG", "name" => "Ganda (Uganda)"],
            ["locale" => "ka", "name" => "Georgian"],
            ["locale" => "ka_GE", "name" => "Georgian (Georgia)"],
            ["locale" => "de", "name" => "German"],
            ["locale" => "de_AT", "name" => "German (Austria)"],
            ["locale" => "de_BE", "name" => "German (Belgium)"],
            ["locale" => "de_DE", "name" => "German (Germany)"],
            ["locale" => "de_LI", "name" => "German (Liechtenstein)"],
            ["locale" => "de_LU", "name" => "German (Luxembourg)"],
            ["locale" => "de_CH", "name" => "German (Switzerland)"],
            ["locale" => "el", "name" => "Greek"],
            ["locale" => "el_CY", "name" => "Greek (Cyprus)"],
            ["locale" => "el_GR", "name" => "Greek (Greece)"],
            ["locale" => "gu", "name" => "Gujarati"],
            ["locale" => "gu_IN", "name" => "Gujarati (India)"],
            ["locale" => "ha", "name" => "Hausa"],
            ["locale" => "ha_GH", "name" => "Hausa (Ghana)"],
            ["locale" => "ha_Latn_GH", "name" => "Hausa (Latin, Ghana)"],
            ["locale" => "ha_Latn_NE", "name" => "Hausa (Latin, Niger)"],
            ["locale" => "ha_Latn_NG", "name" => "Hausa (Latin, Nigeria)"],
            ["locale" => "ha_Latn", "name" => "Hausa (Latin)"],
            ["locale" => "ha_NE", "name" => "Hausa (Niger)"],
            ["locale" => "ha_NG", "name" => "Hausa (Nigeria)"],
            ["locale" => "he", "name" => "Hebrew"],
            ["locale" => "he_IL", "name" => "Hebrew (Israel)"],
            ["locale" => "hi", "name" => "Hindi"],
            ["locale" => "hi_IN", "name" => "Hindi (India)"],
            ["locale" => "hu", "name" => "Hungarian"],
            ["locale" => "hu_HU", "name" => "Hungarian (Hungary)"],
            ["locale" => "is", "name" => "Icelandic"],
            ["locale" => "is_IS", "name" => "Icelandic (Iceland)"],
            ["locale" => "ig", "name" => "Igbo"],
            ["locale" => "ig_NG", "name" => "Igbo (Nigeria)"],
            ["locale" => "id", "name" => "Indonesian"],
            ["locale" => "id_ID", "name" => "Indonesian (Indonesia)"],
            ["locale" => "ga", "name" => "Irish"],
            ["locale" => "ga_IE", "name" => "Irish (Ireland)"],
            ["locale" => "it", "name" => "Italian"],
            ["locale" => "it_IT", "name" => "Italian (Italy)"],
            ["locale" => "it_SM", "name" => "Italian (San Marino)"],
            ["locale" => "it_CH", "name" => "Italian (Switzerland)"],
            ["locale" => "ja", "name" => "Japanese"],
            ["locale" => "ja_JP", "name" => "Japanese (Japan)"],
            ["locale" => "kl", "name" => "Kalaallisut"],
            ["locale" => "kl_GL", "name" => "Kalaallisut (Greenland)"],
            ["locale" => "kn", "name" => "Kannada"],
            ["locale" => "kn_IN", "name" => "Kannada (India)"],
            ["locale" => "ks", "name" => "Kashmiri"],
            ["locale" => "ks_Arab_IN", "name" => "Kashmiri (Arabic, India)"],
            ["locale" => "ks_Arab", "name" => "Kashmiri (Arabic)"],
            ["locale" => "ks_IN", "name" => "Kashmiri (India)"],
            ["locale" => "kk", "name" => "Kazakh"],
            ["locale" => "kk_Cyrl_KZ", "name" => "Kazakh (Cyrillic, Kazakhstan)"],
            ["locale" => "kk_Cyrl", "name" => "Kazakh (Cyrillic)"],
            ["locale" => "kk_KZ", "name" => "Kazakh (Kazakhstan)"],
            ["locale" => "km", "name" => "Khmer"],
            ["locale" => "km_KH", "name" => "Khmer (Cambodia)"],
            ["locale" => "ki", "name" => "Kikuyu"],
            ["locale" => "ki_KE", "name" => "Kikuyu (Kenya)"],
            ["locale" => "rw", "name" => "Kinyarwanda"],
            ["locale" => "rw_RW", "name" => "Kinyarwanda (Rwanda)"],
            ["locale" => "ko", "name" => "Korean"],
            ["locale" => "ko_KP", "name" => "Korean (North Korea)"],
            ["locale" => "ko_KR", "name" => "Korean (South Korea)"],
            ["locale" => "ky", "name" => "Kyrgyz"],
            ["locale" => "ky_Cyrl_KG", "name" => "Kyrgyz (Cyrillic, Kyrgyzstan)"],
            ["locale" => "ky_Cyrl", "name" => "Kyrgyz (Cyrillic)"],
            ["locale" => "ky_KG", "name" => "Kyrgyz (Kyrgyzstan)"],
            ["locale" => "lo", "name" => "Lao"],
            ["locale" => "lo_LA", "name" => "Lao (Laos)"],
            ["locale" => "lv", "name" => "Latvian"],
            ["locale" => "lv_LV", "name" => "Latvian (Latvia)"],
            ["locale" => "ln", "name" => "Lingala"],
            ["locale" => "ln_AO", "name" => "Lingala (Angola)"],
            ["locale" => "ln_CF", "name" => "Lingala (Central African Republic)"],
            ["locale" => "ln_CG", "name" => "Lingala (Congo - Brazzaville)"],
            ["locale" => "ln_CD", "name" => "Lingala (Congo - Kinshasa)"],
            ["locale" => "lt", "name" => "Lithuanian"],
            ["locale" => "lt_LT", "name" => "Lithuanian (Lithuania)"],
            ["locale" => "lu", "name" => "Luba-Katanga"],
            ["locale" => "lu_CD", "name" => "Luba-Katanga (Congo - Kinshasa)"],
            ["locale" => "lb", "name" => "Luxembourgish"],
            ["locale" => "lb_LU", "name" => "Luxembourgish (Luxembourg)"],
            ["locale" => "mk", "name" => "Macedonian"],
            ["locale" => "mk_MK", "name" => "Macedonian (Macedonia)"],
            ["locale" => "mg", "name" => "Malagasy"],
            ["locale" => "mg_MG", "name" => "Malagasy (Madagascar)"],
            ["locale" => "ms", "name" => "Malay"],
            ["locale" => "ms_BN", "name" => "Malay (Brunei)"],
            ["locale" => "ms_Latn_BN", "name" => "Malay (Latin, Brunei)"],
            ["locale" => "ms_Latn_MY", "name" => "Malay (Latin, Malaysia)"],
            ["locale" => "ms_Latn_SG", "name" => "Malay (Latin, Singapore)"],
            ["locale" => "ms_Latn", "name" => "Malay (Latin)"],
            ["locale" => "ms_MY", "name" => "Malay (Malaysia)"],
            ["locale" => "ms_SG", "name" => "Malay (Singapore)"],
            ["locale" => "ml", "name" => "Malayalam"],
            ["locale" => "ml_IN", "name" => "Malayalam (India)"],
            ["locale" => "mt", "name" => "Maltese"],
            ["locale" => "mt_MT", "name" => "Maltese (Malta)"],
            ["locale" => "gv", "name" => "Manx"],
            ["locale" => "gv_IM", "name" => "Manx (Isle of Man)"],
            ["locale" => "mr", "name" => "Marathi"],
            ["locale" => "mr_IN", "name" => "Marathi (India)"],
            ["locale" => "mn", "name" => "Mongolian"],
            ["locale" => "mn_Cyrl_MN", "name" => "Mongolian (Cyrillic, Mongolia)"],
            ["locale" => "mn_Cyrl", "name" => "Mongolian (Cyrillic)"],
            ["locale" => "mn_MN", "name" => "Mongolian (Mongolia)"],
            ["locale" => "ne", "name" => "Nepali"],
            ["locale" => "ne_IN", "name" => "Nepali (India)"],
            ["locale" => "ne_NP", "name" => "Nepali (Nepal)"],
            ["locale" => "nd", "name" => "North Ndebele"],
            ["locale" => "nd_ZW", "name" => "North Ndebele (Zimbabwe)"],
            ["locale" => "se", "name" => "Northern Sami"],
            ["locale" => "se_FI", "name" => "Northern Sami (Finland)"],
            ["locale" => "se_NO", "name" => "Northern Sami (Norway)"],
            ["locale" => "se_SE", "name" => "Northern Sami (Sweden)"],
            ["locale" => "no", "name" => "Norwegian"],
            ["locale" => "no_NO", "name" => "Norwegian (Norway)"],
            ["locale" => "nb", "name" => "Norwegian Bokmål"],
            ["locale" => "nb_NO", "name" => "Norwegian Bokmål (Norway)"],
            ["locale" => "nb_SJ", "name" => "Norwegian Bokmål (Svalbard & Jan Mayen)"],
            ["locale" => "nn", "name" => "Norwegian Nynorsk"],
            ["locale" => "nn_NO", "name" => "Norwegian Nynorsk (Norway)"],
            ["locale" => "or", "name" => "Oriya"],
            ["locale" => "or_IN", "name" => "Oriya (India)"],
            ["locale" => "om", "name" => "Oromo"],
            ["locale" => "om_ET", "name" => "Oromo (Ethiopia)"],
            ["locale" => "om_KE", "name" => "Oromo (Kenya)"],
            ["locale" => "os", "name" => "Ossetic"],
            ["locale" => "os_GE", "name" => "Ossetic (Georgia)"],
            ["locale" => "os_RU", "name" => "Ossetic (Russia)"],
            ["locale" => "ps", "name" => "Pashto"],
            ["locale" => "ps_AF", "name" => "Pashto (Afghanistan)"],
            ["locale" => "fa", "name" => "Persian"],
            ["locale" => "fa_AF", "name" => "Persian (Afghanistan)"],
            ["locale" => "fa_IR", "name" => "Persian (Iran)"],
            ["locale" => "pl", "name" => "Polish"],
            ["locale" => "pl_PL", "name" => "Polish (Poland)"],
            ["locale" => "pt", "name" => "Portuguese"],
            ["locale" => "pt_AO", "name" => "Portuguese (Angola)"],
            ["locale" => "pt_BR", "name" => "Portuguese (Brazil)"],
            ["locale" => "pt_CV", "name" => "Portuguese (Cape Verde)"],
            ["locale" => "pt_GW", "name" => "Portuguese (Guinea-Bissau)"],
            ["locale" => "pt_MO", "name" => "Portuguese (Macau SAR China)"],
            ["locale" => "pt_MZ", "name" => "Portuguese (Mozambique)"],
            ["locale" => "pt_PT", "name" => "Portuguese (Portugal)"],
            ["locale" => "pt_ST", "name" => "Portuguese (São Tomé & Príncipe)"],
            ["locale" => "pt_TL", "name" => "Portuguese (Timor-Leste)"],
            ["locale" => "pa", "name" => "Punjabi"],
            ["locale" => "pa_Arab_PK", "name" => "Punjabi (Arabic, Pakistan)"],
            ["locale" => "pa_Arab", "name" => "Punjabi (Arabic)"],
            ["locale" => "pa_Guru_IN", "name" => "Punjabi (Gurmukhi, India)"],
            ["locale" => "pa_Guru", "name" => "Punjabi (Gurmukhi)"],
            ["locale" => "pa_IN", "name" => "Punjabi (India)"],
            ["locale" => "pa_PK", "name" => "Punjabi (Pakistan)"],
            ["locale" => "qu", "name" => "Quechua"],
            ["locale" => "qu_BO", "name" => "Quechua (Bolivia)"],
            ["locale" => "qu_EC", "name" => "Quechua (Ecuador)"],
            ["locale" => "qu_PE", "name" => "Quechua (Peru)"],
            ["locale" => "ro", "name" => "Romanian"],
            ["locale" => "ro_MD", "name" => "Romanian (Moldova)"],
            ["locale" => "ro_RO", "name" => "Romanian (Romania)"],
            ["locale" => "rm", "name" => "Romansh"],
            ["locale" => "rm_CH", "name" => "Romansh (Switzerland)"],
            ["locale" => "rn", "name" => "Rundi"],
            ["locale" => "rn_BI", "name" => "Rundi (Burundi)"],
            ["locale" => "ru", "name" => "Russian"],
            ["locale" => "ru_BY", "name" => "Russian (Belarus)"],
            ["locale" => "ru_KZ", "name" => "Russian (Kazakhstan)"],
            ["locale" => "ru_KG", "name" => "Russian (Kyrgyzstan)"],
            ["locale" => "ru_MD", "name" => "Russian (Moldova)"],
            ["locale" => "ru_RU", "name" => "Russian (Russia)"],
            ["locale" => "ru_UA", "name" => "Russian (Ukraine)"],
            ["locale" => "sg", "name" => "Sango"],
            ["locale" => "sg_CF", "name" => "Sango (Central African Republic)"],
            ["locale" => "gd", "name" => "Scottish Gaelic"],
            ["locale" => "gd_GB", "name" => "Scottish Gaelic (United Kingdom)"],
            ["locale" => "sr", "name" => "Serbian"],
            ["locale" => "sr_BA", "name" => "Serbian (Bosnia & Herzegovina)"],
            [
                "locale" => "sr_Cyrl_BA",
                "name" => "Serbian (Cyrillic, Bosnia & Herzegovina)",
            ],
            ["locale" => "sr_Cyrl_XK", "name" => "Serbian (Cyrillic, Kosovo)"],
            ["locale" => "sr_Cyrl_ME", "name" => "Serbian (Cyrillic, Montenegro)"],
            ["locale" => "sr_Cyrl_RS", "name" => "Serbian (Cyrillic, Serbia)"],
            ["locale" => "sr_Cyrl", "name" => "Serbian (Cyrillic)"],
            ["locale" => "sr_XK", "name" => "Serbian (Kosovo)"],
            [
                "locale" => "sr_Latn_BA",
                "name" => "Serbian (Latin, Bosnia & Herzegovina)",
            ],
            ["locale" => "sr_Latn_XK", "name" => "Serbian (Latin, Kosovo)"],
            ["locale" => "sr_Latn_ME", "name" => "Serbian (Latin, Montenegro)"],
            ["locale" => "sr_Latn_RS", "name" => "Serbian (Latin, Serbia)"],
            ["locale" => "sr_Latn", "name" => "Serbian (Latin)"],
            ["locale" => "sr_ME", "name" => "Serbian (Montenegro)"],
            ["locale" => "sr_RS", "name" => "Serbian (Serbia)"],
            ["locale" => "sh", "name" => "Serbo-Croatian"],
            ["locale" => "sh_BA", "name" => "Serbo-Croatian (Bosnia & Herzegovina)"],
            ["locale" => "sn", "name" => "Shona"],
            ["locale" => "sn_ZW", "name" => "Shona (Zimbabwe)"],
            ["locale" => "ii", "name" => "Sichuan Yi"],
            ["locale" => "ii_CN", "name" => "Sichuan Yi (China)"],
            ["locale" => "si", "name" => "Sinhala"],
            ["locale" => "si_LK", "name" => "Sinhala (Sri Lanka)"],
            ["locale" => "sk", "name" => "Slovak"],
            ["locale" => "sk_SK", "name" => "Slovak (Slovakia)"],
            ["locale" => "sl", "name" => "Slovenian"],
            ["locale" => "sl_SI", "name" => "Slovenian (Slovenia)"],
            ["locale" => "so", "name" => "Somali"],
            ["locale" => "so_DJ", "name" => "Somali (Djibouti)"],
            ["locale" => "so_ET", "name" => "Somali (Ethiopia)"],
            ["locale" => "so_KE", "name" => "Somali (Kenya)"],
            ["locale" => "so_SO", "name" => "Somali (Somalia)"],
            ["locale" => "es", "name" => "Spanish"],
            ["locale" => "es_AR", "name" => "Spanish (Argentina)"],
            ["locale" => "es_BO", "name" => "Spanish (Bolivia)"],
            ["locale" => "es_IC", "name" => "Spanish (Canary Islands)"],
            ["locale" => "es_EA", "name" => "Spanish (Ceuta & Melilla)"],
            ["locale" => "es_CL", "name" => "Spanish (Chile)"],
            ["locale" => "es_CO", "name" => "Spanish (Colombia)"],
            ["locale" => "es_CR", "name" => "Spanish (Costa Rica)"],
            ["locale" => "es_CU", "name" => "Spanish (Cuba)"],
            ["locale" => "es_DO", "name" => "Spanish (Dominican Republic)"],
            ["locale" => "es_EC", "name" => "Spanish (Ecuador)"],
            ["locale" => "es_SV", "name" => "Spanish (El Salvador)"],
            ["locale" => "es_GQ", "name" => "Spanish (Equatorial Guinea)"],
            ["locale" => "es_GT", "name" => "Spanish (Guatemala)"],
            ["locale" => "es_HN", "name" => "Spanish (Honduras)"],
            ["locale" => "es_MX", "name" => "Spanish (Mexico)"],
            ["locale" => "es_NI", "name" => "Spanish (Nicaragua)"],
            ["locale" => "es_PA", "name" => "Spanish (Panama)"],
            ["locale" => "es_PY", "name" => "Spanish (Paraguay)"],
            ["locale" => "es_PE", "name" => "Spanish (Peru)"],
            ["locale" => "es_PH", "name" => "Spanish (Philippines)"],
            ["locale" => "es_PR", "name" => "Spanish (Puerto Rico)"],
            ["locale" => "es_ES", "name" => "Spanish (Spain)"],
            ["locale" => "es_US", "name" => "Spanish (United States)"],
            ["locale" => "es_UY", "name" => "Spanish (Uruguay)"],
            ["locale" => "es_VE", "name" => "Spanish (Venezuela)"],
            ["locale" => "sw", "name" => "Swahili"],
            ["locale" => "sw_KE", "name" => "Swahili (Kenya)"],
            ["locale" => "sw_TZ", "name" => "Swahili (Tanzania)"],
            ["locale" => "sw_UG", "name" => "Swahili (Uganda)"],
            ["locale" => "sv", "name" => "Swedish"],
            ["locale" => "sv_AX", "name" => "Swedish (Åland Islands)"],
            ["locale" => "sv_FI", "name" => "Swedish (Finland)"],
            ["locale" => "sv_SE", "name" => "Swedish (Sweden)"],
            ["locale" => "tl", "name" => "Tagalog"],
            ["locale" => "tl_PH", "name" => "Tagalog (Philippines)"],
            ["locale" => "ta", "name" => "Tamil"],
            ["locale" => "ta_IN", "name" => "Tamil (India)"],
            ["locale" => "ta_MY", "name" => "Tamil (Malaysia)"],
            ["locale" => "ta_SG", "name" => "Tamil (Singapore)"],
            ["locale" => "ta_LK", "name" => "Tamil (Sri Lanka)"],
            ["locale" => "te", "name" => "Telugu"],
            ["locale" => "te_IN", "name" => "Telugu (India)"],
            ["locale" => "th", "name" => "Thai"],
            ["locale" => "th_TH", "name" => "Thai (Thailand)"],
            ["locale" => "bo", "name" => "Tibetan"],
            ["locale" => "bo_CN", "name" => "Tibetan (China)"],
            ["locale" => "bo_IN", "name" => "Tibetan (India)"],
            ["locale" => "ti", "name" => "Tigrinya"],
            ["locale" => "ti_ER", "name" => "Tigrinya (Eritrea)"],
            ["locale" => "ti_ET", "name" => "Tigrinya (Ethiopia)"],
            ["locale" => "to", "name" => "Tongan"],
            ["locale" => "to_TO", "name" => "Tongan (Tonga)"],
            ["locale" => "tr", "name" => "Turkish"],
            ["locale" => "tr_CY", "name" => "Turkish (Cyprus)"],
            ["locale" => "tr_TR", "name" => "Turkish (Turkey)"],
            ["locale" => "uk", "name" => "Ukrainian"],
            ["locale" => "uk_UA", "name" => "Ukrainian (Ukraine)"],
            ["locale" => "ur", "name" => "Urdu"],
            ["locale" => "ur_IN", "name" => "Urdu (India)"],
            ["locale" => "ur_PK", "name" => "Urdu (Pakistan)"],
            ["locale" => "ug", "name" => "Uyghur"],
            ["locale" => "ug_Arab_CN", "name" => "Uyghur (Arabic, China)"],
            ["locale" => "ug_Arab", "name" => "Uyghur (Arabic)"],
            ["locale" => "ug_CN", "name" => "Uyghur (China)"],
            ["locale" => "uz", "name" => "Uzbek"],
            ["locale" => "uz_AF", "name" => "Uzbek (Afghanistan)"],
            ["locale" => "uz_Arab_AF", "name" => "Uzbek (Arabic, Afghanistan)"],
            ["locale" => "uz_Arab", "name" => "Uzbek (Arabic)"],
            ["locale" => "uz_Cyrl_UZ", "name" => "Uzbek (Cyrillic, Uzbekistan)"],
            ["locale" => "uz_Cyrl", "name" => "Uzbek (Cyrillic)"],
            ["locale" => "uz_Latn_UZ", "name" => "Uzbek (Latin, Uzbekistan)"],
            ["locale" => "uz_Latn", "name" => "Uzbek (Latin)"],
            ["locale" => "uz_UZ", "name" => "Uzbek (Uzbekistan)"],
            ["locale" => "vi", "name" => "Vietnamese"],
            ["locale" => "vi_VN", "name" => "Vietnamese (Vietnam)"],
            ["locale" => "cy", "name" => "Welsh"],
            ["locale" => "cy_GB", "name" => "Welsh (United Kingdom)"],
            ["locale" => "fy", "name" => "Western Frisian"],
            ["locale" => "fy_NL", "name" => "Western Frisian (Netherlands)"],
            ["locale" => "yi", "name" => "Yiddish"],
            ["locale" => "yo", "name" => "Yoruba"],
            ["locale" => "yo_BJ", "name" => "Yoruba (Benin)"],
            ["locale" => "yo_NG", "name" => "Yoruba (Nigeria)"],
            ["locale" => "zu", "name" => "Zulu"],
            ["locale" => "zu_ZA", "name" => "Zulu (South Africa)"],
        ];
    }
}
